<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <Authors>André Kirst</Authors>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <SignAssembly>false</SignAssembly>
    <AssemblyOriginatorKeyFile>DateTimeRangeParserKey.pfx</AssemblyOriginatorKeyFile>
  </PropertyGroup>

</Project>
